### ISSUE TITLE
Error Running tuneinradio addon on Kodi 17.4-6

### ISSUE THREAD

**Issue by adit-s** [brianhornsby/plugin.audio.tuneinradio#111]
Hello. I've used the tuneineradio addon for about 6 months and it's worked without any issues until about a week ago. Now, it generates an error which I think is related to the Favourites category.
I get the same error on a Windows 10 PC with Kodi 17.6 and a Mac (10.12.6) with Kodi 17.4.

Do you have any idea what's causing the problem or if I need to change something to correct it?

Thanks,
A Sood

This is from the error log:
17:35:22.014 T:123145303465984   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'urllib2.HTTPError'>
                                            Error Contents: HTTP Error 403: Forbidden
                                            Traceback (most recent call last):
                                              File "/Users/xx/Library/Application Support/Kodi/addons/plugin.audio.tuneinradio/default.py", line 1029, in <module>
                                                results = __tunein__.browse_presets(username=__username__)
                                              File "/Users/xx/Library/Application Support/Kodi/addons/plugin.audio.tuneinradio/resources/lib/tunein.py", line 368, in browse_presets
                                                result = self.__call_tunein('Browse.ashx', params)
                                              File "/Users/xx/Library/Application Support/Kodi/addons/plugin.audio.tuneinradio/resources/lib/tunein.py", line 103, in __call_tunein
                                                f = urllib2.urlopen(req)
                                              File "/Users/Shared/jenkins/workspace/OSX-64/tools/depends/xbmc-depends/macosx10.10_x86_64-target/lib/python2.7/urllib2.py", line 154, in urlopen
                                              File "/Users/Shared/jenkins/workspace/OSX-64/tools/depends/xbmc-depends/macosx10.10_x86_64-target/lib/python2.7/urllib2.py", line 435, in open
                                              File "/Users/Shared/jenkins/workspace/OSX-64/tools/depends/xbmc-depends/macosx10.10_x86_64-target/lib/python2.7/urllib2.py", line 548, in http_response
                                              File "/Users/Shared/jenkins/workspace/OSX-64/tools/depends/xbmc-depends/macosx10.10_x86_64-target/lib/python2.7/urllib2.py", line 473, in error
                                              File "/Users/Shared/jenkins/workspace/OSX-64/tools/depends/xbmc-depends/macosx10.10_x86_64-target/lib/python2.7/urllib2.py", line 407, in _call_chain
                                              File "/Users/Shared/jenkins/workspace/OSX-64/tools/depends/xbmc-depends/macosx10.10_x86_64-target/lib/python2.7/urllib2.py", line 556, in http_error_default
                                            HTTPError: HTTP Error 403: Forbidden
                                            -->End of Python script error report<--
17:35:22.054 T:140735741309888   ERROR: GetDirectory - Error getting plugin://plugin.audio.tuneinradio/
17:35:22.054 T:140735741309888   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.audio.tuneinradio/) failed

**Comment by jimmytudesky** [comment]
Same here on OSMC 2017.10-1 with Kodi 17.5.

**Comment by brianhornsby** [comment]
Looks like TuneIn might have revoked my access to API (favourites) that requires authorisation.
Not much I can do. The rest of the plugin seems to work ok.

**Comment by adit-s** [comment]
Following the [fix](https://github.com/brianhornsby/plugin.audio.tuneinradio/commit/875749efe5669589029541d60ebeb72a569c5a04#diff-60af07305a47e4fb70987cf05e78e919) for issue #111, I changed the partnerid as described and it fixed the problem (the Favorites are working as before).
In Windows 10, the default.py file needs to be updated (not addon.py). The directory path to the defaults.py is:
~\AppData\Local\Packages\XMBCFoundation...\LocalCache\Roaming\Kodi\addons\plugin.audio.tuneinradio

**Comment by adit-s** [comment]
Thanks for the quick response and writing and maintaining the tunein addon. It is very useful to me and I'm sure a lot of other people too!

**Comment by jimmytudesky** [comment]
Thanks for the quick fix!

**Comment by arabesc** [comment]
I've passed through the parentId fix but there is another issue (I've masked a serail value):
```
17:03:00.112 T:10072   DEBUG: TuneIn Library: DEBUG: Protocol: https://
17:03:00.112 T:10072   DEBUG: TuneIn Library: DEBUG: Global Params: [{'value': 'HyzqumNX', 'param': 'partnerId'}, {'value': 'XX:XX:XX:XX:XX:XX', 'param': 'serial'}, {'value': 'json', 'param': 'render'}, {'value': 'ru-RU', 'param': 'locale'}, {'value': u'aac,mp3,ogg,wma,wmpro,wmvideo,wmvoice', 'param': 'formats'}]
17:03:00.112 T:10072   DEBUG: TuneIn Radio: DEBUG: Addon: TuneIn Radio
17:03:00.112 T:10072   DEBUG: TuneIn Radio: DEBUG: Version: 3.0.0
17:03:00.112 T:10072   DEBUG: TuneIn Radio: DEBUG: Params: tune: {'logo': 'http://cdn-radiotime-logos.tunein.com/s0q.png', 'id': 's1472', 'name': '90.8 | Relax FM -  ', 'path': 'tune'}
17:03:00.112 T:10072   DEBUG: TuneIn Library: DEBUG: tune
17:03:00.112 T:10072   DEBUG: TuneIn Library: DEBUG: id: s1472
17:03:00.112 T:10072   DEBUG: TuneIn Library: DEBUG: URL: https://opml.radiotime.com/Tune.ashx?locale=ru-RU&serial=XXXXXXXXXXXX&partnerId=HyzqumNX&id=s1472&formats=aac%2Cmp3%2Cogg%2Cwma%2Cwmpro%2Cwmvideo%2Cwmvoice
17:03:01.424 T:10072   DEBUG: TuneIn Library: DEBUG: First pass of streams.
17:03:01.427 T:10072   DEBUG: TuneIn Library: DEBUG: stream: #STATUS:
17:03:01.427 T:10072   DEBUG: TuneIn Library: DEBUG: filepath:
17:03:01.427 T:10072   DEBUG: TuneIn Library: DEBUG: filename: #status:
17:03:01.427 T:10072   DEBUG: TuneIn Library: DEBUG: shortname: #status:
17:03:01.427 T:10072   DEBUG: TuneIn Library: DEBUG: extension:
17:03:01.427 T:10072   DEBUG: TuneIn Library: DEBUG: Unknown stream
17:03:01.430 T:10072   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ValueError'>
                                            Error Contents: unknown url type: 
                                            Traceback (most recent call last):
                                              File "C:\Users\kodi\AppData\Roaming\Kodi\addons\plugin.audio.tuneinradio\default.py", line 878, in <module>
                                                result = __tunein__.tune(__id__)
                                              File "C:\Users\kodi\AppData\Roaming\Kodi\addons\plugin.audio.tuneinradio\resources\lib\tunein.py", line 835, in tune
                                                f = opener.open(request)
                                              File "C:\Program Files (x86)\Kodi\system\python\Lib\urllib2.py", line 421, in open
                                                protocol = req.get_type()
                                              File "C:\Program Files (x86)\Kodi\system\python\Lib\urllib2.py", line 283, in get_type
                                                raise ValueError, "unknown url type: %s" % self.__original
                                            ValueError: unknown url type: 
                                            -->End of Python script error report<--
17:03:01.467 T:10072    INFO: Python script stopped
17:03:01.467 T:10072   DEBUG: Thread LanguageInvoker 10072 terminating
```
What is it about?
