### ISSUE TITLE
Can't use a TuneIn account

### ISSUE THREAD

**Issue by scrutinizer80** [brianhornsby/plugin.audio.tuneinradio#113]
Hey there,

I'm unable to use my tunein radio account.
The credentials are configured properly but I get a "Network error" when trying to access
the favorites menu. All other functions work just fine.

On the tunein website settings there's an option to add a device using a "registration code". Should I have gotten it from the plugin at some point?

Thanks!

**Comment by Webklient** [comment]
Same here.

I tried fiddling with all the TuneIn addon settings to no avail.
Running latest TuneIn addon v3.0.2

If your TuneIn addon crashes when you start it, turn the following setting off in the addon.
 - **Only show TuneIn favorites** (**off**)

This way you can still manually search for stations.

**Comment by brianhornsby** [comment]
Duplicate of issue #111

TuneIn appear to have revoked my access to the API methods used for presets. You can fix it manually by editing the default.py file and setting the variable __partnerid__ to ‘HyzqumNX’

Plugin shouldn’t crash if refused access to a user’s TuneIn presets. That’s an issue as well.

Will fix in next release, whenever that is.

**Comment by Webklient** [comment]
Hi Brian

Hope you het this email.

Thanks for the lightning quick reply. 

The ID change on the default.py file worked perfectly. I can see my favourites now.

It also fixed the addon crash, when the "Only show TuneIn favourites" setting is set to on.

Cheers Thanks! 

-------- Original message --------

**Comment by Japetusgr** [comment]
seems like partnerid needs changing again?

**Comment by brianhornsby** [comment]
New partnerid 'HyzqumNX' still seems to be working ok for me.

**Comment by Japetusgr** [comment]
Strange, it works on android, but I can't seem to get it working on libreelec.

**Comment by ratelutz** [comment]
Thanks thats help me to. I was afraid to stop using my main plugin.

**Comment by limonetty** [comment]
Hi,
It works well in raspbian in Kodi 17.4
Thanks

**Comment by danreg** [comment]
sorry for the stupid question, but what is the location of default.py?

**Comment by brianhornsby** [comment]
Operating system | File path
-- | --
Linux | ~/.kodi/addons/plugin.audio.tuneinradio/
Mac | /Users/<your_user_name>/Library/Application Support/Kodi/addons/plugin.audio.tuneinradio/
LibreELEC/OpenELEC | /storage/.kodi/addons/plugin.audio.tuneinradio/

**Comment by arabesc** [comment]
I've passed through the parentId fix but there is another issue (I've masked a serail value):
```
17:03:00.112 T:10072   DEBUG: TuneIn Library: DEBUG: Protocol: https://
17:03:00.112 T:10072   DEBUG: TuneIn Library: DEBUG: Global Params: [{'value': 'HyzqumNX', 'param': 'partnerId'}, {'value': 'XX:XX:XX:XX:XX:XX', 'param': 'serial'}, {'value': 'json', 'param': 'render'}, {'value': 'ru-RU', 'param': 'locale'}, {'value': u'aac,mp3,ogg,wma,wmpro,wmvideo,wmvoice', 'param': 'formats'}]
17:03:00.112 T:10072   DEBUG: TuneIn Radio: DEBUG: Addon: TuneIn Radio
17:03:00.112 T:10072   DEBUG: TuneIn Radio: DEBUG: Version: 3.0.0
17:03:00.112 T:10072   DEBUG: TuneIn Radio: DEBUG: Params: tune: {'logo': 'http://cdn-radiotime-logos.tunein.com/s0q.png', 'id': 's1472', 'name': '90.8 | Relax FM -  ', 'path': 'tune'}
17:03:00.112 T:10072   DEBUG: TuneIn Library: DEBUG: tune
17:03:00.112 T:10072   DEBUG: TuneIn Library: DEBUG: id: s1472
17:03:00.112 T:10072   DEBUG: TuneIn Library: DEBUG: URL: https://opml.radiotime.com/Tune.ashx?locale=ru-RU&serial=XXXXXXXXXXXX&partnerId=HyzqumNX&id=s1472&formats=aac%2Cmp3%2Cogg%2Cwma%2Cwmpro%2Cwmvideo%2Cwmvoice
17:03:01.424 T:10072   DEBUG: TuneIn Library: DEBUG: First pass of streams.
17:03:01.427 T:10072   DEBUG: TuneIn Library: DEBUG: stream: #STATUS:
17:03:01.427 T:10072   DEBUG: TuneIn Library: DEBUG: filepath:
17:03:01.427 T:10072   DEBUG: TuneIn Library: DEBUG: filename: #status:
17:03:01.427 T:10072   DEBUG: TuneIn Library: DEBUG: shortname: #status:
17:03:01.427 T:10072   DEBUG: TuneIn Library: DEBUG: extension:
17:03:01.427 T:10072   DEBUG: TuneIn Library: DEBUG: Unknown stream
17:03:01.430 T:10072   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ValueError'>
                                            Error Contents: unknown url type: 
                                            Traceback (most recent call last):
                                              File "C:\Users\kodi\AppData\Roaming\Kodi\addons\plugin.audio.tuneinradio\default.py", line 878, in <module>
                                                result = __tunein__.tune(__id__)
                                              File "C:\Users\kodi\AppData\Roaming\Kodi\addons\plugin.audio.tuneinradio\resources\lib\tunein.py", line 835, in tune
                                                f = opener.open(request)
                                              File "C:\Program Files (x86)\Kodi\system\python\Lib\urllib2.py", line 421, in open
                                                protocol = req.get_type()
                                              File "C:\Program Files (x86)\Kodi\system\python\Lib\urllib2.py", line 283, in get_type
                                                raise ValueError, "unknown url type: %s" % self.__original
                                            ValueError: unknown url type: 
                                            -->End of Python script error report<--
17:03:01.467 T:10072    INFO: Python script stopped
17:03:01.467 T:10072   DEBUG: Thread LanguageInvoker 10072 terminating
```
What is it about?

**Comment by brianhornsby** [comment]
@arabesc #STATUS 400 usually means that TuneIn does not have a stream for the specified radio station. I have raised issue #114 as plugin should handle this message better.
