### ISSUE TITLE
Plugin error

### ISSUE THREAD

**Issue by mind12** [brianhornsby/plugin.audio.tuneinradio#116]
## Description

Start any station the plugin won't start.
Plugin version 3.0.0, on the latest Kodi 17.

## Debug log

`18:19:12.116 T:6692   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'urllib2.URLError'>
                                            Error Contents: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:661)>
                                            Traceback (most recent call last):
                                              File "C:\Users\kodi\AppData\Roaming\Kodi\addons\plugin.audio.tuneinradio\default.py", line 686, in <module>
                                                __formatscache__.add(tunein.TuneIn(__partnerid__).describe_formats())
                                              File "C:\Users\kodi\AppData\Roaming\Kodi\addons\plugin.audio.tuneinradio\resources\lib\tunein.py", line 592, in describe_formats
                                                result = self.__call_tunein('Describe.ashx', params)
                                              File "C:\Users\kodi\AppData\Roaming\Kodi\addons\plugin.audio.tuneinradio\resources\lib\tunein.py", line 103, in __call_tunein
                                                f = urllib2.urlopen(req)
                                              File "C:\Program Files (x86)\Kodi\system\python\Lib\urllib2.py", line 154, in urlopen
                                                return opener.open(url, data, timeout)
                                              File "C:\Program Files (x86)\Kodi\system\python\Lib\urllib2.py", line 429, in open
                                                response = self._open(req, data)
                                              File "C:\Program Files (x86)\Kodi\system\python\Lib\urllib2.py", line 447, in _open
                                                '_open', req)
                                              File "C:\Program Files (x86)\Kodi\system\python\Lib\urllib2.py", line 407, in _call_chain
                                                result = func(*args)
                                              File "C:\Program Files (x86)\Kodi\system\python\Lib\urllib2.py", line 1241, in https_open
                                                context=self._context)
                                              File "C:\Program Files (x86)\Kodi\system\python\Lib\urllib2.py", line 1198, in do_open
                                                raise URLError(err)
                                            URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:661)>
                                            -->End of Python script error report<--
18:19:12.186 T:6932   ERROR: PlayMedia could not play media: plugin://plugin.audio.tuneinradio/?logo=http%3A%2F%2Fcdn-radiotime-logos.tunein.com%2Fs121038q.png&id=s121038&name=Class+FM&path=tune`
`

**Comment by brianhornsby** [comment]
Looks like there was a issue with the website certificate that my plugin was trying to access.
Nothing to do with my plugin, so closing issue.

**Comment by radekhodal** [comment]
thanks your answer

ADRESA:
Radek Hodál
Pražmo 159
okr. Frýdek-Místek
739 04
*Tel: 608824199*
*radekhodal@email.cz <radekhodal@email.cz>*
radekhodal@gmail.com

2018-02-23 7:58 GMT+01:00 Brian Hornsby <notifications@github.com>:
