### ISSUE TITLE
Unable to play triple j

### ISSUE THREAD

**Issue by guest3** [brianhornsby/plugin.audio.tuneinradio#83]
With Australia Day just a couple of days away, I was hoping to listen to the Triple J Hotest 100 using the Tunein addon but I am unable to do so, the output of the xbmc log when trying to play the Triple J stream is below:

13:48:02 T:139902280750848   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'ConfigParser.NoOptionError'>
                                            Error Contents: No option 'NumberOfEntries' in section: 'playlist'
                                            Traceback (most recent call last):
                                              File "/home/user/.xbmc/addons/plugin.audio.tuneinradio/default.py", line 877, in <module>
                                                result = **tunein**.tune(**id**)
                                              File "/home/user/.xbmc/addons/plugin.audio.tuneinradio/resources/lib/tunein.py", line 803, in tune
                                                for stream in self.__parse_pls(stream):
                                              File "/home/user/.xbmc/addons/plugin.audio.tuneinradio/resources/lib/tunein.py", line 165, in __parse_pls
                                                numentries = config.getint('playlist', 'NumberOfEntries')
                                              File "/usr/lib/python2.7/ConfigParser.py", line 359, in getint
                                                return self._get(section, int, option)
                                              File "/usr/lib/python2.7/ConfigParser.py", line 356, in _get
                                                return conv(self.get(section, option))
                                              File "/usr/lib/python2.7/ConfigParser.py", line 340, in get
                                                raise NoOptionError(option, section)
                                            NoOptionError: No option 'NumberOfEntries' in section: 'playlist'
                                            -->End of Python script error report<--
13:48:02 T:139903533139904   ERROR: Playlist Player: skipping unplayable item: 43, path [plugin://plugin.audio.tuneinradio/?logo=http%3A%2F%2Fcdn-radiotime-logos.tunein.com%2Fs25508q.png&path=tune&id=s89108&name=triple+j+101.5+%28Alternative+Rock%29]

**Comment by brianhornsby** [comment]
I won't be able to get a fix out before Australia Day, but a temporary workaround is to enter the following  url for Triple J using the Custom URL menu option. 
http://abc.stream.hostworks.com.au/aac or http://abc.stream.hostworks.com.au/mp3

**Comment by guest3** [comment]
Thanks for your prompt response Brian! Australia Day wouldn't be complete without listening to the Triple J Hottest 100 and you've come up with the goods!

**Comment by brianhornsby** [comment]
Unable to reproduce in latest development branch.
